/**
 * CORTEX PARTNER AGREEMENT — VERSION 1.0
 *
 * This file contains the approved text for Cortex Partner Agreement Version 1.0,
 * drawn directly from docs/partner-program/03-PARTNER-AGREEMENT-V1.0.md.
 *
 * DO NOT edit this file to change existing versions. If the agreement terms change,
 * create a new version constant (e.g., AGREEMENT_V1_1) and update CURRENT_AGREEMENT_VERSION.
 *
 * Historical acceptance records reference the version string (e.g., "1.0").
 * This ensures every Partner's acceptance can be traced to the exact text they agreed to.
 *
 * Source document status: Draft for legal/business review before production enforcement.
 * See docs/partner-program/03-PARTNER-AGREEMENT-V1.0.md for the authoritative source.
 */

export const CURRENT_AGREEMENT_VERSION = "1.0";

export const PARTNER_AGREEMENT_V1_0 = `
CORTEX PARTNER AGREEMENT
Version 1.0

IMPORTANT: This agreement is a draft for legal/business review before production acceptance.


1. PURPOSE

This Agreement establishes the working relationship between The Cortex Systems ("Cortex") and an approved Cortex Partner ("Partner") for the identification, development, and delivery of software and digital solutions.


2. INDEPENDENT RELATIONSHIP

The Partner participates as an independent business partner. This Agreement does not, by itself, create an employment relationship, joint venture, agency, or partnership in the legal sense between Cortex and the Partner.

Neither party may represent that it has authority to bind the other unless expressly authorized.


3. PARTNER RESPONSIBILITIES

The Partner is responsible for:

- Identifying potential customers and software opportunities.
- Maintaining the customer relationship.
- Accurately communicating customer requirements.
- Submitting project opportunities through the Cortex Partner Platform.
- Providing complete and accurate project information.
- Coordinating customer feedback where appropriate.
- Reviewing completed work.
- Delivering the completed solution to the customer.

The Partner must not promise features, timelines, prices, warranties, or services on behalf of Cortex that Cortex has not approved.


4. CORTEX RESPONSIBILITIES

Cortex is responsible for the technical development services it agrees to provide for an accepted project.

Cortex will assess project opportunities and determine whether and how a project can be developed.

Cortex is not obligated to accept every opportunity submitted by a Partner.


5. WHITE-LABEL / BEHIND-THE-SCENES ARRANGEMENT

The Partner may present the completed solution to its customer as part of the Partner's own customer relationship, subject to the terms and limitations of this Agreement.

Cortex will ordinarily operate as the Partner's behind-the-scenes technical development provider.

Cortex will not unnecessarily interfere with the Partner's customer relationship.

Nothing in this section prevents Cortex from communicating directly when reasonably necessary for technical, security, payment, legal, support, or project-delivery reasons, or where otherwise agreed.


6. PROJECT-BY-PROJECT APPROVAL

Each project is separately assessed and agreed.

Submitting an opportunity does not guarantee acceptance, development, or delivery.

The approved project scope, pricing, timeline, and conditions apply to that specific project.


7. PRICING AND PARTNER MARGIN

Cortex will provide the Partner with applicable Partner pricing or project commercial terms.

The Partner may determine its customer-facing price unless the applicable project terms state otherwise.

The difference between the Partner's customer price and the applicable Cortex charge may constitute the Partner's commercial margin.

No specific margin or income is guaranteed.


8. PROJECT SCOPE

Development is based on the agreed project scope.

Requests outside the agreed scope may be treated as additional work and may require separate pricing, timeline, or approval.


9. CUSTOMER AND PROJECT INFORMATION

The Partner should initially submit only the information necessary for opportunity assessment.

After a project is won, the Partner must provide the information required for development, including applicable branding, content, media, domain, integration, and technical information.

The Partner must have the appropriate authority to provide information and materials submitted for a project.


10. INTELLECTUAL PROPERTY AND CUSTOMER MATERIALS

Ownership and licensing of software, designs, content, trademarks, images, and other materials must be determined by the applicable project terms and any separate agreements.

A Partner must not submit materials it does not have permission to use.

Cortex retains ownership of its pre-existing tools, libraries, reusable components, know-how, and infrastructure unless otherwise expressly agreed.


11. CONFIDENTIALITY

Each party should protect confidential business, technical, customer, pricing, and project information received from the other party.

Confidential information should only be used for legitimate purposes connected with the Partner Program and applicable projects.


12. SECURITY AND CREDENTIALS

Partners must not unnecessarily submit passwords or sensitive credentials through ordinary project forms.

Where technical access is required, the approved secure process must be used.

Partners must protect their account credentials and must not share Partner-platform login credentials.


13. CUSTOMER RELATIONSHIP

The Partner is responsible for its customer relationship.

The Partner should manage customer expectations, requirements, feedback, and customer-facing communication.

Cortex should not solicit or deliberately interfere with a Partner's customer relationship through the Partner Program.

This does not prevent Cortex from protecting its legitimate business, legal, security, payment, or contractual interests.


14. CHANGES AND REVISIONS

Project changes must be submitted through the approved Change Request process where applicable.

Cortex will assess whether a request is within the agreed scope.

Additional work may require additional charges or a revised timeline.


15. DELIVERY

The Partner reviews completed work through the platform.

Once the Partner provides the required delivery approval, the Partner may proceed with customer delivery according to the project arrangement.


16. SUPPORT

Technical support requests should be submitted through the Cortex Partner Platform.

Support availability and response expectations may depend on the applicable project or support arrangement.


17. PARTNER CONDUCT

Partners are expected to operate professionally and honestly.

A Partner must not:

- Misrepresent Cortex's services.
- Misrepresent the Partner Program.
- Submit fraudulent projects.
- Misuse confidential information.
- Upload unauthorized customer materials.
- Attempt to access another Partner's projects or information.
- Circumvent platform security.
- Make unauthorized commitments on behalf of Cortex.


18. SUSPENSION OR TERMINATION

Cortex may suspend or terminate Partner access where there is a material breach of this Agreement, misuse of the platform, fraudulent activity, security risk, or other legitimate reason consistent with the applicable agreement and law.

A Partner may also end its participation subject to completion or resolution of outstanding project obligations.

Termination does not automatically erase existing project, payment, confidentiality, intellectual property, or other obligations that are intended to survive termination.


19. NO GUARANTEED PROJECTS OR EARNINGS

Participation does not guarantee customers, projects, revenue, or earnings.


20. AGREEMENT VERSION

This Agreement is Version 1.0.

When a Partner accepts it electronically, the platform records:

- Partner
- Agreement version
- Acceptance timestamp
- Applicable acceptance record

The accepted historical version remains identifiable.


21. GOVERNING TERMS

Applicable governing law, jurisdiction, notices, dispute-resolution provisions, liability limitations, and other formal legal provisions must be finalized through appropriate legal review before this Agreement is used as the final production agreement.


22. ACCEPTANCE

By electronically accepting the approved Partner Agreement Version 1.0, the Partner confirms that they have reviewed and agree to the applicable terms.

---

LEGAL REVIEW REQUIRED BEFORE PRODUCTION USE.
`.trim();

/**
 * Returns the agreement text for a given version string.
 * Used to display the correct historical text if needed.
 */
export function getAgreementText(version: string): string | null {
  if (version === "1.0") return PARTNER_AGREEMENT_V1_0;
  return null;
}
